// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWK7dhFbzDqapSQtxlebVg209eBZUNx5c',
    appId: '1:235277619668:web:894e2d1419fc1c77b50641',
    messagingSenderId: '235277619668',
    projectId: 'pckapp2-fadbf',
    authDomain: 'pckapp2-fadbf.firebaseapp.com',
    storageBucket: 'pckapp2-fadbf.appspot.com',
    measurementId: 'G-LNLKMLXDXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_dYuQAfpIEW4fe9ypHp6x32ctpMhMZ7s',
    appId: '1:235277619668:android:3bbc3a1d3523dd3bb50641',
    messagingSenderId: '235277619668',
    projectId: 'pckapp2-fadbf',
    storageBucket: 'pckapp2-fadbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdwlUawOqYKJTcGG-6Jtn5eY_DW9LI7s0',
    appId: '1:235277619668:ios:0ca1ce80021f2b80b50641',
    messagingSenderId: '235277619668',
    projectId: 'pckapp2-fadbf',
    storageBucket: 'pckapp2-fadbf.appspot.com',
    iosBundleId: 'com.example.pckapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdwlUawOqYKJTcGG-6Jtn5eY_DW9LI7s0',
    appId: '1:235277619668:ios:0ca1ce80021f2b80b50641',
    messagingSenderId: '235277619668',
    projectId: 'pckapp2-fadbf',
    storageBucket: 'pckapp2-fadbf.appspot.com',
    iosBundleId: 'com.example.pckapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWK7dhFbzDqapSQtxlebVg209eBZUNx5c',
    appId: '1:235277619668:web:fb1bd5353fb44f65b50641',
    messagingSenderId: '235277619668',
    projectId: 'pckapp2-fadbf',
    authDomain: 'pckapp2-fadbf.firebaseapp.com',
    storageBucket: 'pckapp2-fadbf.appspot.com',
    measurementId: 'G-8ZE43QZXH4',
  );

}